base_path: .
preserve_hierarchy: true
files:
  - source: glasscutter-common/src/main/resources/assets/glasscutter/lang/en_us.json
    translation: glasscutter-common/src/main/resources/assets/glasscutter/lang/%locale_with_underscore%.json
