"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "."
"preserve_hierarchy": true
"files": [
  {
    "source": "/glasscutter-common/src/main/resources/assets/glasscutter/lang/en_us.json",
    "translation": "/glasscutter-common/src/main/resources/assets/glasscutter/lang/%locale_with_underscore%.json",
    "languages_mapping": {
      "locale_with_underscore": {
        "af_ZA": "af_za",
        "an_ES": "an_es",
        "arn_CL": "arn_cl",
        "ar_SA": "ar_sa",
        "ast_ES": "ast_es",
        "av_DA": "av_da",
        "az_AZ": "az_az",
        "ba_RU": "ba_ru",
        "be_BY": "be_by",
        "bg_BG": "bg_bg",
        "bn_BD": "bn_bd",
        "br_FR": "br_fr",
        "bs_BA": "bs_ba",
        "ca_ES": "ca_es",
        "ce_CE": "ce_ce",
        "ckb_IR": "ckb_ir",
        "csb_PL": "csb_pl",
        "cs_CZ": "cs_cz",
        "cv_CU": "cv_cu",
        "cy_GB": "cy_gb",
        "da_DK": "da_dk",
        "de_AT": "de_at",
        "de_CH": "de_ch",
        "de_DE": "de_de",
        "dsb_DE": "dsb_de",
        "el_GR": "el_gr",
        "en_AU": "en_au",
        "en_CA": "en_ca",
        "en_GB": "en_gb",
        "en_NZ": "en_nz",
        "en_PT": "en_pt",
        "en_UD": "en_ud",
        "eo_UY": "eo_uy",
        "es_AR": "es_ar",
        "es_CL": "es_cl",
        "es_CO": "es_co",
        "es_CR": "es_cr",
        "es_EC": "es_ec",
        "es_ES": "es_es",
        "es_MX": "es_mx",
        "es_PE": "es_pe",
        "es_UY": "es_uy",
        "es_VE": "es_ve",
        "et_EE": "et_ee",
        "eu_ES": "eu_es",
        "fa_IR": "fa_ir",
        "fil_PH": "fil_ph",
        "fi_FI": "fi_fi",
        "fo_FO": "fo_fo",
        "fra_DE": "fra_de",
        "fr_CA": "fr_ca",
        "fr_CH": "fr_ch",
        "fr_FR": "fr_fr",
        "fur_IT": "fur_it",
        "fy_NL": "fy_nl",
        "ga_IE": "ga_ie",
        "gd_GB": "gd_gb",
        "gl_ES": "gl_es",
        "gn_PY": "gn_py",
        "got_DE": "got_de",
        "gv_IM": "gv_im",
        "haw_US": "haw_us",
        "he_IL": "he_il",
        "hi_IN": "hi_in",
        "hr_HR": "hr_hr",
        "hsb_DE": "hsb_de",
        "hu_HU": "hu_hu",
        "hy_AM": "hy_am",
        "id_ID": "id_id",
        "ig_NG": "ig_ng",
        "io_EN": "io_en",
        "is_IS": "is_is",
        "it_IT": "it_it",
        "ja_JP": "ja_jp",
        "jbo_EN": "jbo_en",
        "kab_KAB": "kab_kab",
        "ka_GE": "ka_ge",
        "kk_KZ": "kk_kz",
        "kn_IN": "kn_in",
        "ko_KR": "ko_kr",
        "kw_GB": "kw_gb",
        "ky_KG": "ky_kg",
        "la_LA": "la_la",
        "lb_LU": "lb_lu",
        "li_LI": "li_li",
        "lol_US": "lol_us",
        "lo_LA": "lo_la",
        "lt_LT": "lt_lt",
        "lv_LV": "lv_lv",
        "me_ME": "me_me",
        "mi_NZ": "mi_nz",
        "mk_MK": "mk_mk",
        "mn_MN": "mn_mn",
        "moh_CA": "moh_ca",
        "ms_MY": "ms_my",
        "mt_MT": "mt_mt",
        "nds_DE": "nds_de",
        "ne_NP": "ne_np",
        "nl_BE": "nl_be",
        "nl_NL": "nl_nl",
        "nn_NO": "nn_no",
        "no_NO": "no_no",
        "oc_FR": "oc_fr",
        "oj_CA": "oj_ca",
        "pa_IN": "pa_in",
        "pl_PL": "pl_pl",
        "pt_BR": "pt_br",
        "pt_PT": "pt_pt",
        "qya_AA": "qya_aa",
        "ro_RO": "ro_ro",
        "ru_RU": "ru_ru",
        "ry_UA": "ry_ua",
        "sah_SAH": "sah_sah",
        "se_NO": "se_no",
        "sk_SK": "sk_sk",
        "sl_SI": "sl_si",
        "so_SO": "so_so",
        "sq_AL": "sq_al",
        "sr_CS": "sr_cs",
        "sr_Cyrl_ME": "sr_cyrl_me",
        "sr_SP": "sr_sp",
        "sv_SE": "sv_se",
        "ta_IN": "ta_in",
        "th_TH": "th_th",
        "tlh_AA": "tlh_aa",
        "tl_PH": "tl_ph",
        "tr_TR": "tr_tr",
        "tt_RU": "tt_ru",
        "tzl_TZL": "tzl_tzl",
        "ug_CN": "ug_cn",
        "uk_UA": "uk_ua",
        "ur_PK": "ur_pk",
        "uz_UZ": "uz_uz",
        "val_ES": "val_es",
        "vec_IT": "vec_it",
        "vi_VN": "vi_vn",
        "yi_DE": "yi_de",
        "yo_NG": "yo_ng",
        "zh_CN": "zh_cn",
        "zh_HK": "zh_hk",
        "zh_TW": "zh_tw"
      }
    }
  }
]